# Copyright 2019 The Periph Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

os: linux
dist: bionic
language: go
go_import_path: periph.io/x/gohci

jobs:
  include:
  - go: 1.14.x
    cache:
      directories:
      - $GOPATH/pkg/mod
    before_script:
    - echo $TRAVIS_GO_VERSION
    - go get -t -v periph.io/x/gohci/...
    - >
      go get -u -v
      golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
    script:
    - >
      echo 'Erroring on shadowed variables:';
      ! go vet -vettool=$(which shadow) ./... |& grep -v '"err"' | grep -e '^[^#]'
